# Generated by Django 2.2.28 on 2022-04-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220428_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='izena',
            field=models.CharField(max_length=60),
        ),
    ]
